### PR TITLE
simplify tests

### PR DESCRIPTION
**Pull request by IonBazan**
### What is the reason for this PR?

This PR removes a lot of duplicated code and refactors all the tests. This replaces the previous PR without style changes (sorry for that) #90.

### Summary of changes

- [x] Initializing `Generator` instance for each test in `setUp` method
- [x] Sets the seed to `1` to make results predictable
- [x] Adding `protected function getProviders(): iterable` allowing developers to easily specify providers needed in the test
- [x] Migrated most of `$this->assert*` and `$this->fail()` to static calls
- [x] Uses dedicated `assertNotContains` or `assertGreaterThan` assertions instead of asserting that comparison returns `false`

### Review checklist

- [x] All checks have passed
- [ ] Changes are approved by maintainer

### CODE REVIEW

**Comment by mfn** [comment]
> Migrated most of `$this->assert*` and `$this->fail()` to static calls

This should be enforced via the style checker so no manual work and future contributions automatically adhere to the same style, see https://github.com/FakerPHP/Faker/pull/90#issuecomment-736646450

**Comment by IonBazan** [comment]
@mfn Unfortunately, StyleCI does not support `php_unit_test_case_static_method_calls` fixer: https://github.styleci.io/analyses/Yjmr4G

**Comment by GrahamCampbell** [comment]
StyleCI will do soon. :)

**Comment by bramceulemans** [comment]
Can this be merged? @GrahamCampbell

**Pull request merged**
