### PR TITLE
Add brand new logo to the project

### PR DESCRIPTION
**Pull request by caneco**
### What is the reason for this PR?

Here's the brand new logo for the FakerPHP package, as requested in #44 😉 

socialcard

I hope you like it 😊

### CODE REVIEW

**Comment by bramceulemans** [comment]
You made a typo in the social GitHub image.

Also we made an artwork repository, I think this is better fitted for that.

**Comment by GrahamCampbell** [comment]
I don't think we should upload the artwork to this repo because of the filesize.

**Comment by bramceulemans** [comment]
https://github.com/FakerPHP/artwork

Can someone with permission capitalize the repo? @pimjansen

**Comment by olivernybroe** [comment]
Thanks! I love the logo 👍 hope to see this being the logo soon ♥️

**Comment by localheinz** [comment]
@bramceulemans 

> Can someone with permission capitalize the repo? @pimjansen

What do you mean by that?

**Comment by bramceulemans** [comment]
> @bramceulemans 
> 
> > Can someone with permission capitalize the repo? @pimjansen
> 
> What do you mean by that?

The repository name 😅

**Comment by pimjansen** [comment]
Will close this PR since it belongs in the dedicated repo instead. I just merged it over there

**Comment by caneco** [comment]
> Will close this PR since it belongs in the dedicated repo instead. I just merged it over there

Sorry about the `/art` folder, but also, no README banner in the header?

**Pull request closed without merging**
