### PR TITLE
Enabled more StyleCI fixers

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Review by Nyholm — COMMENTED** [review]
This feels soo nice to clean up the CI =)

Could you give me a link to the docs where I can see what these new rules really mean?

**Comment by GrahamCampbell** [comment]
https://docs.styleci.io/fixers

**Comment by Nyholm** [comment]
Thank you. Im happy with these changes.

**Comment by Nyholm** [comment]
Could you finish up this PR? It will be easier to continue work if there isnt a lot of merge conflicts later on.

**Comment by GrahamCampbell** [comment]
Will pass after https://github.com/FakerPHP/Faker/pull/47 is merged, and then I rebase this.

**Pull request merged**
