### PR TITLE
Introduce the Color provider for "pl_PL" locale

### PR DESCRIPTION
**Pull request by d1823**
### What is the reason for this PR?

- [x] A new feature
- [ ] Fixed an issue (resolve #ID)

### Author's checklist

- [x] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [x] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)

### Summary of changes

This PR introduces a dedicated Color provider for the "pl_PL" locale. 

### Review checklist

- [ ] All checks have passed
- [ ] Changes are approved by maintainer

### CODE REVIEW

**Comment by pimjansen** [comment]
tests are missing

**Comment by d1823** [comment]
I've added some tests based on the existing - french - color test cases.

**Comment by pimjansen** [comment]
> I've added some tests based on the existing - french - color test cases.

Yeah its hard to test since it has datalists but since we use seeds it will always return the same result. So in this case we are sure it keeps running like this and that there are atleast no sidefx

**Review by pimjansen — APPROVED** [review]
Lgtm

**Pull request merged**
