### PR TITLE
Enhancement: Check in composer.lock for development tools

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] checks in `composer.lock` for development tools

Follows #131.

### CODE REVIEW

**Comment by mfn** [comment]
Why would we want that?

**Comment by localheinz** [comment]
@mfn 

Because:

- we want to use Dependabot
- we want reproducible builds

**Comment by mfn** [comment]
@localheinz thank you!

**Comment by localheinz** [comment]
@mfn 

You are welcome!

**Pull request merged**
