### PR TITLE
Removed the name Adolf and similarities

### PR DESCRIPTION
**Pull request by Joas707**
### What is the reason for this PR?

In a few data sets, there was a name Adolf, Adolph or something similar. It is not appropriate to give the name Adolph to a person, as it is associated with Adolf Hitler, who was the leader of Nazi Germany during World War II and responsible for the deaths of millions of people, including six million Jews. The use of this name would be offensive and inappropriate, as it is associated with one of the most heinous regimes in history. 

This fix is especially useful for people who use this database for seeding test data what will be seen by management and possible customers. This wil avoid misunderstandings. 

- [ ] A new feature
- [x] Fixed an issue (resolve #ID)

### Author's checklist

- [ ] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [ ] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)

### Summary of changes

See upper paragraph

### Review checklist

- [x] All checks have passed
- [ ] Changes are approved by maintainer

### CODE REVIEW

**Comment by pimjansen** [comment]
We do not just update datasets since someone does not agree with the content overall. Adolf is a common German name so i do not really see any problem here?

@localheinz as a native can you shed some light maybe?

**Comment by bram-pkg** [comment]
It really isn't a common name anymore for anybody born after the 40s. I
think this would be fine to remove, to be honest.
Nobody calls their kid Adolf in Germany anymore, for obvious reasons.

**Comment by pimjansen** [comment]
@Joas707 can you ensure only the name Adolf is removed?

**Comment by Joas707** [comment]
Yes of course! But in that case I suggest to also remove Adolph as well, because that name is so similar, especially in spoken language.

**Comment by localheinz** [comment]
@pimjansen 

>We do not just update datasets since someone does not agree with the content overall. Adolf is a common German name so i do not really see any problem here?
>
>@localheinz as a native can you shed some light maybe?

I have found an [article from 2018](https://m.faz.net/aktuell/gesellschaft/menschen/adolf-als-vorname-kann-man-seinem-kind-einen-belasteten-namen-geben-15704445.amp.html) that claims that (at the time of writing) 46.171 people still have that name in Germany. I believe, however, that the name is not very popular in Germany.

Regardless, I recall @fzaninotto arguing against removing (or modifying) data sets. I guess it depends on how people use the generated data. I do not care much about the data itself, just that the data makes some sense in the context I use it in. 

Given that variations of the name in other languages may be popular in the countries where these languages are spoken, I am not sure what the best approach would be here.

**Review by bram-pkg — APPROVED** [review]
LGTM!

**Comment by bram-pkg** [comment]
You should look up how many new kids are being born that call their kid Adolf.

**Comment by ioSeoGio** [comment]
Do you know who also drank water? Hitler

**Pull request merged**
