### PR TITLE
Fix: sk_SK street names

### LINKED ISSUE #672: Incorect output value for sk_SK location from streetName
### Summary

streetName for sk_SK location is returning not valid local values. For example "Jakubová Parks". The second word is in english, not in slovak. It should be "Jakubová ulica" for example (Jakubová Street in english).

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 7.4.0   |
| `fakerphp/faker`  | 1.23.0   |

### Self-enclosed code snippet for reproduction

```php
echo $faker->streetName()
```

### Expected output

```txt
Jakubova ulica
```

### Actual output

```txt
Jakubova Parks
```

### PR DESCRIPTION
**Pull request by devicebusy**
### What is the reason for this PR?

Fixed an issue with sk_SK street names generation (resolve #672)

### Author's checklist

- [x] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [x] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)

### Summary of changes

Added a list of real SK streets, fixed street name format

### Review checklist

- [ ] All checks have passed
- [ ] Changes are approved by maintainer

### CODE REVIEW

**Comment by pimjansen** [comment]
Please review the contribution guide (see pr template)

**Review by localheinz — APPROVED** [review]

**Comment by localheinz** [comment]
@pimjansen 

This looks good to me - do you have any objections?

**Comment by pimjansen** [comment]
> @pimjansen 
> 
> 
> 
> This looks good to me - do you have any objections?

The code itself looks ok but i'd rather see the locale contents covered by a test

**Comment by MilosM33** [comment]
@pimjansen Hello, I'd like to reopen and finalize this Pull Request. What specific test would you like to see?

**Pull request closed without merging**
