### PR TITLE
Add logo to README

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Replaces https://github.com/FakerPHP/Faker/pull/242.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
// cc @caneco, @pimjansen

**Review by chris-doehring — APPROVED** [review]
Thanks @GrahamCampbell

**Comment by pimjansen** [comment]
Isnt the socialcatd github build for this @GrahamCampbell ?

**Comment by caneco** [comment]
The file `socialcard-github` it's for the social preview setting of every repo (I guess).

The other `socialcard` it's more for the OpenGraph image

**Pull request merged**
