### PR TITLE
Add Microsoft Edge User Agent

### PR DESCRIPTION
**Pull request by dutchie027**
### What is the reason for this PR?

This pull request adds the MS Edge User Agent. 

- [x] A new feature
- [ ] Fixed an issue (resolve #ID)

### Author's checklist

- [x] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [x] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io) - [PR#64](https://github.com/FakerPHP/fakerphp.github.io/pull/64)

### Summary of changes

The Microsoft Edge User Agent was added in the User Agent Provider. It can generate an Edge UA for Windows, Linux, Mac and also iOS. To support iOS, the iOS device function was also added to the User Agent Provider.

A test was written to search for "Edg" when calling this user agent as that is the commonality among all Ednge UAs. (Edg, EdgA and EdgiOS respectively are the three different "distinct" Edge UAs.)

[PR for documentation submitted](https://github.com/FakerPHP/fakerphp.github.io/pull/64)

### Review checklist

- [ ] All checks have passed
- [ ] Changes are approved by maintainer

### CODE REVIEW

**Comment by bram-pkg** [comment]
Please revert the change in the Person provider. Otherwise this looks good.

**Comment by pimjansen** [comment]
> should I push the person change in another commit?

No we are not just randomly adding names since people want their own

**Comment by pimjansen** [comment]
Do we have some source refs on how these look for Edge? PR looks fine but have to cross check to be sure

**Comment by dutchie027** [comment]
Here is my current user agent:

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.46

[The latest user agents for Edge
](https://www.whatismybrowser.com/guides/the-latest-user-agent/edge)

**Comment by pimjansen** [comment]
Ok thanks for the list, looks good. What still is missing is the addition in the Generator phpdoc. Since all calls to legacy are still made using a __call it is required.

**Comment by dutchie027** [comment]
Copy. Didn't see that in the "Best Practices" area. Should be in Generator.php now for doc and autocompletion.

**Comment by pimjansen** [comment]
> Copy. Didn't see that in the "Best Practices" area. Should be in Generator.php now for doc and autocompletion.

Yeah it is until we reach v2. Mostly because static type tools like psalm and phpstan complain if it is not.

Will give it a last review tomorrow but i think we are good to go. Maybe @bram-pkg finds some time earlier though

**Comment by bram-pkg** [comment]
Fixed that last style error for you.

**Review by bram-pkg — APPROVED** [review]

**Comment by bram-pkg** [comment]
The problem probably was that php-cs-fixer doesn't like linting between
different versions of PHP. Try running it on PHP 7.1 next time :)

**Comment by robbinjanssen** [comment]
There is a bug in this PR, i've fixed it in https://github.com/FakerPHP/Faker/pull/469

**Pull request merged**
