### PR TITLE
Update French regions list, remove TOM

### PR DESCRIPTION
**Pull request by ker0x**
### What is the reason for this PR?

- [ ] A new feature
- [x] Fixed an issue

### Author's checklist

- [x] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [ ] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)

### Summary of changes

Since 2015 and the NOTRe law, French regions have been merged. Moreover, Saint-Pierre-et-Miquelon, Saint-Barthélémy, Saint-Martin, Wallis-et-Futuna, Polynésie française and the Nouvelle-Calédonie are TOM, not ROM.

https://en.wikipedia.org/wiki/Regions_of_France

### Review checklist

- [ ] All checks have passed
- [ ] Changes are approved by maintainer

### CODE REVIEW

**Comment by pimjansen** [comment]
Missing reference data. Where is it coming from to verify. Please add it with an @see tag

**Comment by ker0x** [comment]
@pimjansen Done.

**Review by pimjansen — CHANGES_REQUESTED** [review]

**Comment by pimjansen** [comment]
> @pimjansen Done.

See feedback

**Comment by ker0x** [comment]
@pimjansen I just fixed the tests as requested

**Review by pimjansen — APPROVED** [review]

**Comment by pimjansen** [comment]
Very good! Thanks for contributing

**Pull request merged**
