### PR TITLE
Improve test consistency

### PR DESCRIPTION
**Pull request by krsriq**
The tests have a rather high variance of formatting, docblock usage, closing php tags and the test class namespaces were wrong in same cases.
This PR cleans the tests up somewhat.

### CODE REVIEW

**Comment by mfn** [comment]
I wonder why the style fixer doesn't pick up most of them @GrahamCampbell ?

**Comment by krsriq** [comment]
Maybe because styleci is configured to only include src @mfn ?
https://github.com/FakerPHP/Faker/blob/af4a5cecf2cb1b1d0fa50aa73177ec648e1ffd6a/.styleci.yml#L43-L45

**Comment by pimjansen** [comment]
@GrahamCampbell maybe just also include the tests dir for styleci? Thoughts?

**Comment by GrahamCampbell** [comment]
Thanks. :)

**Pull request merged**
