### PR TITLE
add blood types

### PR DESCRIPTION
**Pull request by IonBazan**
This PR:

- [x] Adds a new feature for generating blood type/Rh/group 
- [x] Covered by tests

Some countries use `0` instead of `O` (Poland and some post-SU countries) but I was not able to find a complete list of those so it's not localized.

### CODE REVIEW

**Comment by pimjansen** [comment]
Good addition but dont know if the person provider is best for this change.

Would it not be better to split if off?

**Comment by IonBazan** [comment]
Moved to `Medical`. We can add there more related stuff like allergies or popular medical conditions.

**Comment by bramceulemans** [comment]
This looks fine to me.

**Comment by pimjansen** [comment]
Thanks for contributing

**Review by pimjansen — APPROVED** [review]

**Pull request merged**
