### PR TITLE
Feature/baseline

### PR DESCRIPTION
**Pull request by pimjansen**
### What is the reason for this PR?

Update build state

- [ ] A new feature
- [x] Fixed an issue

### Author's checklist

- [x] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [x] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)

### Summary of changes

After the dependabot updates of PHPStan and Psalm the baseline did not get an update. Which this PR the baseline is refreshed. I also updated a quick reference from an internal call (direct access) to function access

### Review checklist

- [x] All checks have passed
- [ ] Changes are approved by maintainer

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
wtf:

image

🤣 I guess GitHub have a bug here...

**Comment by pimjansen** [comment]
> wtf:
> 
> 
> 
> image
> 
> 
> 
> 🤣 I guess GitHub have a bug here...

Github gone mad haha. It ran now so its ready for approval

**Review by bramceulemans — APPROVED** [review]
Looks good to me.

**Comment by pimjansen** [comment]
Thanks guys!

**Pull request merged**
