### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by bram-pkg**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
BC Check needs fixing.

**Comment by bram-pkg** [comment]
> BC Check needs fixing.

Those changes were made in experimental classes.

**Comment by GrahamCampbell** [comment]
In which case the bc yml config file needs adjusting to permit the change. The CI should never be in a failing state. I have adjusted the config to mandate the passing of that job to prevent such a mistake in the future.

**Comment by bram-pkg** [comment]
Rebased on `main`. Ready for review now.

**Review by pimjansen — APPROVED** [review]

**Pull request merged**
