### PR TITLE
Added Lorem and Text in Hebrew (he_IL)

### PR DESCRIPTION
**Pull request by MordiSacks**
### What is the reason for this PR?

- [x] A new feature
- [ ] Fixed an issue (resolve #ID)

### Author's checklist

- [x] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [ ] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)

### Summary of changes

I Added Lorem and Text in Hebrew (he_IL).
The text is The Little Prince By Antoine de Saint-Exupéry
from wiki source
https://he.wikisource.org/wiki/%D7%94%D7%A0%D7%A1%D7%99%D7%9A_%D7%94%D7%A7%D7%98%D7%9F

This was initially sent to `fzaninotto/Faker` here
https://github.com/fzaninotto/Faker/pull/1842
but was put on hold for version 2.0 (which never came unfortunately)
If it is decided eventually to separate faker into core + locales, I will be very happy to maintain the Hebrew locale.

### Review checklist

- [x] All checks have passed
- [ ] Changes are approved by maintainer

### CODE REVIEW

**Comment by pimjansen** [comment]
Missing tests

**Comment by MordiSacks** [comment]
On it...

**Comment by MordiSacks** [comment]
I add a test for Text but I could not find any other locale with a lorem test, the main English does not make much sense to me as, as far as I can tell it does not use the generator, but only asserts agents preset sentences, which to me seems  to defeat the purpose of testing, Am I missing something?  
Thanks.

**Comment by MordiSacks** [comment]
Ok, I can see that my branch is quite behind now I was using phpunit 5.7, I will redo this PR and add more Hebrew and Israel related generators.

**Pull request closed without merging**
