### PR TITLE
Enhancement: Allow installation of psr/container:^2.0.0

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] allows installation of `psr/container:^2.0.0`

### CODE REVIEW

**Comment by pimjansen** [comment]
I think we can allow this for future right?

**Comment by localheinz** [comment]
@pimjansen 

Does not currently work because of different method signatures (`psr/container:2.0.0` adds type and return type declarations).

**Comment by pimjansen** [comment]
> @pimjansen 
> 
> 
> 
> Does not currently work because of different method signatures (`psr/container:2.0.0` adds type and return type declarations).

Fair enough. I think we could force it later though for example in a 3.x where we make the BC or something later on

**Comment by IonBazan** [comment]
@localheinz I think we can just change it to `has(string $id): bool` to support both v1 and v2. This class is not fall under BC promise:
https://github.com/FakerPHP/Faker/blob/98130c68c8a15784524cc7b38829525b0f0c08aa/src/Faker/Extension/Container.php#L12

**Pull request closed without merging**
