### PR TITLE
add `Lorem.php` file For Persian Language (fa_IR)

### PR DESCRIPTION
**Pull request by mehrshaddarzi**
### What is the reason for this PR?

- [x] A new feature
- [ ] Fixed an issue (resolve #ID)

### Author's checklist

- [x] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [ ] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)

### Review checklist

- [x] All checks have passed
- [x] Changes are approved by maintainer

### CODE REVIEW

**Comment by pimjansen** [comment]
Please review the contribution guide.

- build is failing
- tests are missing
- no source provided for the data

**Comment by mehrshaddarzi** [comment]
@thisissorna

Please Help to Complete this PR.

**Comment by thisissorna** [comment]
> @thisissorna
> 
> Please Help to Complete this PR.

Please use the text from the third paragraph from [طرح نما](https://fa.wikipedia.org/wiki/%D8%B7%D8%B1%D8%AD%E2%80%8C%D9%86%D9%85%D8%A7) for creating an array of words and also insert the link as a reference.

**Comment by bram-pkg** [comment]
Closing this for now.

@mehrshaddarzi please add tests and make sure the Coding Standards action is passing.

**Pull request closed without merging**
