### PR TITLE
Update `randomElements` to return random number of elements when no count is provided

### PR DESCRIPTION
**Pull request by CalebDW**
Hello!

### What is the reason for this PR?

This updates `randomElements` to return a random number of elements when no count is provided. Defaulting to a count of 1 is undesirable because if I only wanted one element I would just use `randomElement`. This cleans up having to pass `fake()->numberBetween(1, count($array))` as the `$count` when I don't care how many values are returned.

- [ ] A new feature
- [ ] Fixed an issue (resolve #ID)

### Author's checklist

- [x] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [x] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)

### Summary of changes
- Made `$count` in `Base::randomElement` nullable, and if null, then default to random number of elements.
- Updated documentation

### Review checklist

- [ ] All checks have passed
- [ ] Changes are approved by maintainer

### CODE REVIEW

**Comment by bram-pkg** [comment]
Unfortunately changing the default value of a parameter is a breaking change if it changes the output of the function.

**Comment by CalebDW** [comment]
I understand, can we merge to the next major version though? I don't think it really makes sense to have to explicitly pass `null` to `$count` for this to behave as it reads.

Or I suppose I could change the default back to `1`, and then on the next major release we could update the default value

**Comment by bram-pkg** [comment]
Indeed, I think allowing `null` to get a random number of elements sounds fine, but the signature cannot change within 1.x, sorry.

**Comment by CalebDW** [comment]
@bram-pkg done, is there a planned `2.x` release date?

**Comment by bram-pkg** [comment]
Not as of yet. We're struggling to be motivated I think, outside our day jobs :)

**Review by bram-pkg — APPROVED** [review]

**Comment by DvDty** [comment]
@bram-pkg can the community help with this?

**Comment by CalebDW** [comment]
That's a good idea, it would be helpful if a 'Roadmap to 2.0' issue was created with what needs to be done and then the community could pitch in

**Comment by pimjansen** [comment]
> That's a good idea, it would be helpful if a 'Roadmap to 2.0' issue was created with what needs to be done and then the community could pitch in

Will work on that

**Pull request merged**
