### PR TITLE
Enhancement: Added support for BCP47 / IETF language tags

### PR DESCRIPTION
**Pull request by adrianrudnik**
### What is the reason for this PR?

Use case: Using an API Platform based project, the user chooses a locale for display of UI language, number and date formatting based on the browsers BCP 47 language tags.

The UI itself uses Javascript, so the [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) namespace is used there. The classes and functions available there operate around a [BCP 47](https://en.wikipedia.org/wiki/IETF_language_tag) language tag maintained by the [IANA Language Subtag Registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry). While similar, they are not the same. It is simple to derive a [PHP Locale](https://www.php.net/manual/en/class.locale.php) from that BCP 47 language tag, it is not as easy the other way around.

The goal is allow Faker to produce valid BCP 47 / IETF language tags (either with subtag or not).

Is this a worthwhile addition before I invest time into the documentation?

In addition I  get errors on `make test` about locale based providers, i.e. `InvalidArgumentException: Unable to find provider "Ietf" with locale "ar_EG"`, not sure why, I tried to stick with the `NumberProvider` for the implementation but must have missed something. `getProviderClassname` does not seem to fall back here.

- [x] A new feature
- [ ] Fixed an issue (resolve #ID)

### Author's checklist

- [x] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [ ] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)

### Review checklist

- [ ] All checks have passed
- [ ] Changes are added to the `CHANGELOG.md`
- [ ] Changes are approved by maintainer

### CODE REVIEW

**Comment by adrianrudnik** [comment]
Ah thank you for the hint. I'll take a look and migrate it to 2.x if possible. Should I close this PR or reuse it for that?

**Comment by localheinz** [comment]
@adrianrudnik 

Let's keep it open!

**Comment by pimjansen** [comment]
Since it depends on intl i dont see this going in the main core repo of faker. Best is to provide a custom provider that can easily be added as an extension

**Comment by bram-pkg** [comment]
> Since it depends on intl i dont see this going in the main core repo of faker. Best is to provide a custom provider that can easily be added as an extension

I don't see any of the code referencing the intl extension?

**Comment by pimjansen** [comment]
> > Since it depends on intl i dont see this going in the main core repo of faker. Best is to provide a custom provider that can easily be added as an extension
> 
> 
> 
> I don't see any of the code referencing the intl extension?

Ah crap i was wrong. My bad

**Pull request closed without merging**
