### PR TITLE
Added "Thing" Provider

### PR DESCRIPTION
**Pull request by christianitis**
### What is the reason for this PR?

I wanted to a way to generate fake objects, devices, and so on.

- [x] A new feature
- [ ] Fixed an issue (resolve #ID)

### Author's checklist

- [x] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [x] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)

### Summary of changes

Added a new Provider for objects. Generates a name or short description of a fake device, mechanism, etc.
Includes an implementation for the en_US locale.

### Review checklist

- [ ] All checks have passed
- [ ] Changes are approved by maintainer

### CODE REVIEW

**Comment by bram-pkg** [comment]
It would be nice if you could sort the dataset by alphabet, and provide a source for the data.

**Comment by christianitis** [comment]
> It would be nice if you could sort the dataset by alphabet, and provide a source for the data.

I'd be happy to alphabetically sort the data. The source was my brain, I just thought of them off the top of my head.

**Comment by christianitis** [comment]
@bram-pkg Any update on this?

**Comment by christianitis** [comment]
> I dont see any benefit of adding this to the 1.x core tbh

I needed to generate fake hardware for an inventory management system at work, so I figured I'd just upload the changes I made myself for anyone else who might need to do something similar.

**Pull request closed without merging**
