### PR TITLE
Other Brazilian names

### PR DESCRIPTION
**Pull request by robertoarruda**

### CODE REVIEW

**Comment by pimjansen** [comment]
@robertoarruda could you please indicate where the change is for and where the data is from?

**Comment by robertoarruda** [comment]
> @robertoarruda could you please indicate where the change is for and where the data is from?

This commit is just to add more Brazilian names to reduce cases of repeated names.

I didn't use any specific fonts, just names I know.

**Comment by Nyholm** [comment]
Please dont make unrelated CS changes in your PR. It makes it harder to review. 

Please revert those.

**Comment by robertoarruda** [comment]
> Please dont make unrelated CS changes in your PR. It makes it harder to review.
> 
> Please revert those.

Sorry @Nyholm, but this commit just adds names to arrays and changes to short array syntax.

**Comment by Nyholm** [comment]
I see. Thank you. 

Could you please revert the changes to the short array syntax.

**Review by Nyholm — APPROVED** [review]
Thank you. 

Im happy with this PR now. 

-------

Feel free to open a new PR where you change the style rules, and then let Style CI fix the style for the full project.

**Pull request merged**
