### PR TITLE
Fix regex dot/backslash issue

### PR DESCRIPTION
**Pull request by krsriq**
### What is the reason for this PR?

There are two bugs in `regexify` that make #134 fail: when `regexify` is called with a dot (matches any character in regex), the dot may get replaced (by `asciify`) with a backslash, which is an escape character:
https://github.com/FakerPHP/Faker/blob/c65e3b63f556be95d9e3725d872c79654c09b23e/src/Faker/Provider/Base.php#L533

Secondly, all backslashes are removed - even the ones that are escaped:
https://github.com/FakerPHP/Faker/blob/c65e3b63f556be95d9e3725d872c79654c09b23e/src/Faker/Provider/Base.php#L535

- [x] Fixed an issue
- [x] Covered by tests

### Author's checklist

- [x] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [ ] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)

### Summary of changes

This PR fixes the issues by checking whether `asciify` returns a backsash. In case it does it adds another backslash as escape character. 
Additionally escaped backslashes are not removed by `regexify` any more.

### Review checklist

- [ ] All checks have passed
- [ ] Changes are approved by maintainer

### CODE REVIEW

**Review by pimjansen — APPROVED** [review]

**Comment by pimjansen** [comment]
Needs rebase

**Comment by krsriq** [comment]
@pimjansen - done!

**Comment by pimjansen** [comment]
Phpcs is not green yet

**Comment by krsriq** [comment]
Too quick with these style changes 😁

**Pull request merged**
