### PR TITLE
Added missing method for Hungarian married female lastnames

### LINKED ISSUE #502: Hungarian name generation is broken
### Summary

Hungarian name generation is broken, with the message:

> Unknown format "lastNameFemaleMarried"  In Generator.php line 731

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8.1 |
| `fakerphp/faker`  | 1.20   |

### Self-enclosed code snippet for reproduction

```php
class UserFixtures extends Fixture
{
    protected Generator $faker;

    public function __construct()
    {
        $this->faker = Factory::create('hu_HU');
    }

    public function load(ObjectManager $manager): void
    {
        $user = (new User)->setName($this->faker->name());
        $manager->persist($user);
        $manager->flush();
    }
}
```

### Expected output

```txt
no error
```

### Actual output

```txt
error
```
possibly caused by of https://github.com/FakerPHP/Faker/pull/451

cc [zsoltjanes](https://github.com/zsoltjanes) as the author of said PR

### PR DESCRIPTION
**Pull request by pimjansen**
### What is the reason for this PR?

- [ ] A new feature
- [x] Fixed an issue (resolve #502 )

### Author's checklist

- [x] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [ ] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)

### Summary of changes

Added missing method

### Review checklist

- [x] All checks have passed
- [x] Changes are approved by maintainer

### CODE REVIEW

**Review by mmarton — APPROVED** [review]
LGTM

**Review by mmarton — APPROVED** [review]

**Comment by bram-pkg** [comment]
@pimjansen quick tests maybe?

**Comment by pimjansen** [comment]
> @pimjansen quick tests maybe?

Yeah didnt do it yet since there are none for this Locale at all and had some time constraints.

Will add them

**Comment by pimjansen** [comment]
@bram-pkg added basic test

**Review by bram-pkg — APPROVED** [review]

**Comment by bram-pkg** [comment]
Just the cs-fixer check is failing now

**Comment by pimjansen** [comment]
> Just the cs-fixer check is failing now

Yeah booboo as usual 😭

**Pull request merged**
