### PR TITLE
Add DateTime to `Persian` Provider

### PR DESCRIPTION
**Pull request by milwad-dev**
### What is the reason for this PR?

- [x] A new feature

### Author's checklist

- [ ] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [ ] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)

### Summary of changes

I added DateTime to Persian provider.

### Review checklist

- [ ] All checks have passed
- [ ] Changes are added to the `CHANGELOG.md`
- [ ] Changes are approved by maintainer

### CODE REVIEW

**Comment by milwad-dev** [comment]
If this PR is accepted, I will add it to the documentation.

**Comment by pimjansen** [comment]
Did you read the contribution guide and the PR template?

**Comment by milwad-dev** [comment]
Can we draft this PR until the PHPFaker opens for new features?

**Comment by pimjansen** [comment]
> Can we draft this PR until the PHPFaker opens for new features?

No that will be messy since the architecture will change.

But where are the tests?

**Comment by milwad-dev** [comment]
I'm closing it and re-creating it after the architecture changes.
I created this PR and went on holiday but didn't have enough time to write tests.

**Pull request closed without merging**
