### PR TITLE
Update Person.php

### PR DESCRIPTION
**Pull request by melinda-roussel**
Hi,
French names are not combination of first name and last name.
In the list of $lastName you have already enough name to mix and match. They are different of last names.

fr_BE and fr_CH are correctly set so why fr_FR not ?

### CODE REVIEW

**Comment by bram-pkg** [comment]
A full name most definitely includes a first name, right? If you only want last names, use the last name method.

**Comment by melinda-roussel** [comment]
Yeah I agree with you but when you look at the code, names are set as full name (e.g.: {{firstNameMale}} {{lastName}}) so we have no issue to get only "{{lastName}}". That's the problem.

**Comment by pimjansen** [comment]
I still do not understand what you mean? If you want the lastname, pull it from the method?

**Comment by melinda-roussel** [comment]
Hi Pimjansen and Bram

I've just realized that I'm using version 1.9, which is very old and does not have the lastname() method, only a name() method. This is why it was confusing.

Sorry for the inconvenience.

**Pull request closed without merging**
