### PR TITLE
PHP 8.4 Support

### PR DESCRIPTION
**Pull request by Jubeki**
### What is the reason for this PR?

- [ ] A new feature
- [x] Fixed an issue

### Author's checklist

- [x] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [x] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)

### Summary of changes

- Adds PHP 8.4 to Test Matrix
- Add explicit nullable declarations to remove PHP 8.4 deprecations.
- Add `nullable_type_declaration_for_default_null_value` to Coding Standards

### Review checklist

- [ ] All checks have passed
- [ ] Changes are added to the `CHANGELOG.md`
- [ ] Changes are approved by maintainer

### CODE REVIEW

**Comment by pimjansen** [comment]
Thanks! Will review later. Initially it all looks fine

**Comment by Jubeki** [comment]
I think the Static analysis / Psalm failure is unrelated to this PR.

**Review by crynobone — APPROVED** [review]

**Comment by pimjansen** [comment]
> I think the Static analysis / Psalm failure is unrelated to this PR.

Well im not even getting them locally indeed.

**Comment by pimjansen** [comment]
@localheinz you got an idea what this could be? Also the error makes no direct sense to me at all

**Comment by pimjansen** [comment]
Can we recreate the baseline here?

**Comment by Jubeki** [comment]
@pimjansen I have updated the baseline.

**Comment by Jubeki** [comment]
Seems like there is still a problem with the baseline.

I updated it using the following command:

```
vendor/bin/psalm --no-progress --update-baseline
```

(Never used psalm before)

**Comment by pimjansen** [comment]
Me neither so thats why i pinged @localheinz haha. Since i want this PR to be done so we can continue in other libs as well

**Comment by Jubeki** [comment]
@pimjansen Okay I have found the problem regarding the baseline.

The option `--update-baseline` will only removed solved problems from the baseline, it will not add new ones. For that you need to run `--set-baseline=psalm.baseline.xml`.

I have now added a regenrated psalm baseline, which should make this PR mergeable.

**Comment by pimjansen** [comment]
LGTM, cant somehow not merge this via mobile will review tomorrow and push for a 1.24 release

**Review by pimjansen — APPROVED** [review]

**Comment by pimjansen** [comment]
Good work!

**Comment by Jubeki** [comment]
Thanks!

**Pull request merged**
