### PR TITLE
Make Doctrine populator compatible with newer versions of Doctrine

### LINKED ISSUE #149: Doctrine\Common\Persistence vs Doctrine\Persistence
### Summary

Older versions of Doctrine use `Doctrine\Common\Persistence` while newer versions moved to `Doctrine\Persistence` as the namespace for classes like `ObjectManager`

In the original repository, there was already an open discussion (and MR) for this: https://github.com/fzaninotto/Faker/pull/2059
https://github.com/fzaninotto/Faker/issues/2055

I'm not 100% sure how long we should support both versions of Doctrine or how this backwards compatibility should be tackled. (Perhaps a major version upgrade? Or 2 separate Populators?)

### PR DESCRIPTION
**Pull request by jlHertel**
### What is the reason for this PR?
As described in https://github.com/FakerPHP/Faker/issues/149 Doctrine changed some of it's namespaces recently. This change will make the code work with both the new and the old namespace.

- [X] Fixed an issue (resolve #149)

### Author's checklist

- [X] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)

### Summary of changes

Adding namespace checks to make the code compatible with both Doctrine 2.7 and Doctrine 2.8+

### Review checklist

- [ ] All checks have passed
- [ ] Changes are approved by maintainer

### CODE REVIEW

**Comment by jlHertel** [comment]
About BC breaks:
```
[BC] CHANGED: Type documentation for property Faker\ORM\Doctrine\Populator#$manager changed from \Doctrine\Common\Persistence\ObjectManager|null to \Doctrine\Common\Persistence\ObjectManager|\Doctrine\Persistence\ObjectManager|null
[BC] CHANGED: The parameter $manager of Faker\ORM\Doctrine\Populator#__construct() changed from ?Doctrine\Common\Persistence\ObjectManager to no type
[BC] CHANGED: The parameter $class of Faker\ORM\Doctrine\ColumnTypeGuesser#guessFormat() changed from Doctrine\Common\Persistence\Mapping\ClassMetadata to no type
[BC] CHANGED: Type documentation for property Faker\ORM\Doctrine\EntityPopulator#$class changed from \Doctrine\Common\Persistence\Mapping\ClassMetadata to \Doctrine\Common\Persistence\Mapping\ClassMetadata|\Doctrine\Persistence\Mapping\ClassMetadata
[BC] CHANGED: The parameter $class of Faker\ORM\Doctrine\EntityPopulator#__construct() changed from Doctrine\Common\Persistence\Mapping\ClassMetadata to no type
[BC] CHANGED: The parameter $manager of Faker\ORM\Doctrine\EntityPopulator#execute() changed from Doctrine\Common\Persistence\ObjectManager to no type
```

Those changes are intentional, as they make the code compatible with both versions.

**Comment by jlHertel** [comment]
About Psalm and PHPStan analyzes: We are checking for two different package versions and I think composer won't allow us to install both. We can probably add some `@phpstan-ignore-next-line`, but I'm not sure this will also solve the issue for PSalm.

**Comment by pimjansen** [comment]
> About Psalm and PHPStan analyzes: We are checking for two different package versions and I think composer won't allow us to install both. We can probably add some `@phpstan-ignore-next-line`, but I'm not sure this will also solve the issue for PSalm.

We now resolve it with its class reference. What will it do on a named string?

**Comment by jlHertel** [comment]
> We now resolve it with its class reference. What will it do on a named string?
Sorry I'm not sure I understood your question. Can you please elaborate?

**Comment by pimjansen** [comment]
> > We now resolve it with its class reference. What will it do on a named string?
> 
> Sorry I'm not sure I understood your question. Can you please elaborate?

```php
if (!($class instanceof \Doctrine\Common\Persistence\Mapping\ClassMetadata || $class instanceof \Doctrine\Persistence\Mapping\ClassMetadata)) {

vs

if (!($class instanceof '\Doctrine\Common\Persistence\Mapping\ClassMetadata' || $class instanceof '\Doctrine\Persistence\Mapping\ClassMetadata')) {
```

This due the fact you reference a class that might not be there. As a string this will never be the case

**Comment by jlHertel** [comment]
> ```
> if (!($class instanceof \Doctrine\Common\Persistence\Mapping\ClassMetadata || $class instanceof \Doctrine\Persistence\Mapping\ClassMetadata)) {
> 
> vs
> 
> if (!($class instanceof '\Doctrine\Common\Persistence\Mapping\ClassMetadata' || $class instanceof '\Doctrine\Persistence\Mapping\ClassMetadata')) {
> ```
> 
> This due the fact you reference a class that might not be there. As a string this will never be the case

`instanceof` expects a valid class name. If you give it a string it will thrown an error like this:
`PHP Parse error:  syntax error, unexpected single-quoted string "\Doctrine\Common\Persistence\M...`

On the positive side, I think we can just use `get_class()`. Let me update the PR and see how it goes.

**Comment by jlHertel** [comment]
@pimjansen Can you unblock the pipeline again please?

**Comment by jlHertel** [comment]
It seems since version 1.3 of `doctrine/persistence` that the classes exist in the new namespace and are [aliased][1]. Looking in the `doctrine/orm` package, anything above 2.7 should be able to use `doctrine/persistence` above 1.3 without issues.
With this in mind, I think we can safely use the new namespace and add a conflict statement to the `composer.json` to not accept `doctrine/persistence` lower than `1.3`.

@pimjansen What do you think?

[1]: https://github.com/doctrine/persistence/blob/1.3.0/lib/Doctrine/Common/Persistence/ObjectManager.php#L19

**Comment by GrahamCampbell** [comment]
I've pushed some changes here to make it behave as if we had an actual union type on there.

**Comment by jlHertel** [comment]
@GrahamCampbell Note that PHPStan will continue to complain, as it seems we use properties of classes directly, even if we ask just for an interface.

**Comment by pimjansen** [comment]
@GrahamCampbell ping

**Comment by GrahamCampbell** [comment]
Re-gen the baseline file, and ship it.

**Comment by pimjansen** [comment]
> Re-gen the baseline file, and ship it.

Will do thanks

**Comment by GrahamCampbell** [comment]
Not stale.

**Comment by pimjansen** [comment]
With a new baseline this errors keeps showing up:

```
ERROR: UndefinedDocblockClass - src/Faker/ORM/Doctrine/ColumnTypeGuesser.php:19:15 - Docblock-defined class, interface or enum named Doctrine\Persistence\Mapping\ClassMetadata does not exist (see https://psalm.dev/200)
     * @param ClassMetadata|LegacyClassMetadata $class
```

**Comment by bram-pkg** [comment]
Closing this for now.

**Pull request closed without merging**
