### PR TITLE
allow deprecation-contracts v3.0

### PR DESCRIPTION
**Pull request by jrushlow**
### What is the reason for this PR?

Allow using faker with Symfony 6 projects that utilize `symfony/deprecation-contracts` `^v3.0.0`

- [x] A new feature
- [ ] Fixed an issue (resolve #ID)

### Author's checklist

- [ ] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [ ] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)

### Summary of changes

No code based changes required. Allows `symfony/deprecation-contracts` v2.2 || v3.0

### Review checklist

- [ ] All checks have passed
- [ ] Changes are approved by maintainer

### CODE REVIEW

**Review by pimjansen — APPROVED** [review]

**Comment by GrahamCampbell** [comment]
Hmm, who broke the BC check build?

**Comment by jrushlow** [comment]
The 2 CI failures appear to be unrelated. Looking in PR #396 - the same failures exist.

**Comment by GrahamCampbell** [comment]
Thanks. :)

**Comment by GrahamCampbell** [comment]
This will be included in the v1.17.0 release. I should have some time this weekend to look into getting that out the door.

**Pull request merged**
