### PR TITLE
updates to en_za/internet

### PR DESCRIPTION
**Pull request by mikerockett**
### What is the reason for this PR?

Add data to the ZA Internet provider namespace (TLDs).

### Author's checklist

- [x] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [ ] ~~New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)~~ (not applicable)

### Summary of changes

This adds gTLDs, the commonly used .africa, and increases the likelihood of a .co.za or .com being used.

### Review checklist

- [ ] All checks have passed
- [ ] Changes are approved by maintainer

### CODE REVIEW

**Comment by pimjansen** [comment]
Can we sort them as mention in the contribution guide?

**Comment by mikerockett** [comment]
@pimjansen Happy to sort them, however I'm not seeing it mentioned in the contribution guide (am I missing something?), and the original list was not sorted (except that it matched the order of the linked wiki).

**Comment by mikerockett** [comment]
Thanks!

**Comment by GrahamCampbell** [comment]
This should not have been merged with the BC check failing. The BC check config should have been adjusted to explicitly allow this break. I've adjusted the repo config to block this going forward.

**Pull request merged**
