### PR TITLE
Bugfix/ro ro first and last day of year

### PR DESCRIPTION
**Pull request by scybulski**
This PR:

- [ ] Adds a new feature ...
- [ ] Covered by tests
- [x] Fixes date generation in Romanian person generator during leap years
When running in February of a leap year tests fail because invalid date is generated, for example 1959-02-29 which then gets passed to 1959-03-01 and makes tests fail.
<details><summary>Example test result</summary>

```
vagrant@ubuntu-focal:/vagrant$ sudo date -s "21 FEB 2020 18:00:00"
Fri Feb 21 18:00:00 UTC 2020
vagrant@ubuntu-focal:/vagrant$ php vendor/phpunit/phpunit/phpunit test/Faker/Provider/ro_RO/PersonTest.php
PHPUnit 9.4.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.12
Configuration: /vagrant/phpunit.xml.dist

.E............................................E.............................                                                                                                                         76 / 76 (100%)

Time: 00:00.024, Memory: 6.00 MB

There were 2 errors:

1) Faker\Test\Provider\ro_RO\PersonTest::test_validGender_returnsValidCnp
InvalidArgumentException: Invalid date of birth - '1906-03-01' generated based on '' received

/vagrant/src/Faker/Provider/ro_RO/Person.php:182
/vagrant/src/Faker/Provider/ro_RO/Person.php:125
/vagrant/src/Faker/Generator.php:232
/vagrant/src/Faker/Generator.php:289
/vagrant/test/Faker/Provider/ro_RO/PersonTest.php:119

2) Faker\Test\Provider\ro_RO\PersonTest::test_validCountyCode_returnsValidCnp with data set #28 ('MS')
InvalidArgumentException: Invalid date of birth - '2037-03-01' generated based on '' received

/vagrant/src/Faker/Provider/ro_RO/Person.php:182
/vagrant/src/Faker/Provider/ro_RO/Person.php:125
/vagrant/src/Faker/Generator.php:232
/vagrant/src/Faker/Generator.php:289
/vagrant/test/Faker/Provider/ro_RO/PersonTest.php:168

ERRORS!
Tests: 76, Assertions: 76, Errors: 2.
vagrant@ubuntu-focal:/vagrant$ php vendor/phpunit/phpunit/phpunit test/Faker/Provider/ro_RO/PersonTest.php
PHPUnit 9.4.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.12
Configuration: /vagrant/phpunit.xml.dist

......................................E.....................................                                                                                                                         76 / 76 (100%)

Time: 00:00.026, Memory: 6.00 MB

There was 1 error:

1) Faker\Test\Provider\ro_RO\PersonTest::test_validCountyCode_returnsValidCnp with data set #20 ('GJ')
InvalidArgumentException: Invalid date of birth - '1959-03-01' generated based on '' received

/vagrant/src/Faker/Provider/ro_RO/Person.php:182
/vagrant/src/Faker/Provider/ro_RO/Person.php:125
/vagrant/src/Faker/Generator.php:232
/vagrant/src/Faker/Generator.php:289
/vagrant/test/Faker/Provider/ro_RO/PersonTest.php:168

ERRORS!
Tests: 76, Assertions: 77, Errors: 1.
```
</details>

I was not able to write a simple test which would set a current time. Merging this will ensure tests pass in February 2024 and following leap years.

This PR was opened originally [here](https://github.com/fzaninotto/Faker/pull/1942) but never got merged. Back in February all PRs were failing in that repo.

### CODE REVIEW

**Review by chris-doehring — APPROVED** [review]
Thank you for this PR! Looks good to me.

**Comment by bramceulemans** [comment]
I thought BC Check got disabled for the default provider array.

**Comment by pimjansen** [comment]
> I thought BC Check got disabled for the default provider array.

Yes, can we rebase this with main quickly?

**Comment by scybulski** [comment]
> > I thought BC Check got disabled for the default provider array.
> 
> Yes, can we rebase this with main quickly?

Done.

**Pull request merged**
