### PR TITLE
Update namespaces of Doctrine ORM integration

### PR DESCRIPTION
**Pull request by Alymosul**
This PR changes the namespaces used for Doctrine from
`/Doctrine/Common/*` to  `/Doctrine/Persistence` to match namespace in Doctrine2
and is just the same work originally introduced here: [https://github.com/fzaninotto/Faker/pull/2059](url)

### CODE REVIEW

**Comment by pimjansen** [comment]
This is a breaking change and not something that can end up in 1.x though.

For the next major i think i would be way better for this to be a standalone package instead

**Comment by GrahamCampbell** [comment]
I think we need to look for both the old and new class names.

**Comment by Alymosul** [comment]
@GrahamCampbell do you think it would be a solution to copy the same classes (Populator, EntityPopulator,..etc) under `Doctrine2` dir?

**Comment by pimjansen** [comment]
> I think we need to look for both the old and new class names.

Will make it more complex but will deffenitly work for the time being.

**Comment by bramceulemans** [comment]
There seem to be conflicts. Can you rebase?

**Comment by GrahamCampbell** [comment]
I think we need to support both the old and new class names in the 1.x series.

**Comment by pimjansen** [comment]
> I think we need to support both the old and new class names in the 1.x series.

Indeed, we could check if class exists on the new doctrine class as default and load the other if not?

And if none found throw a proper exception

**Pull request closed without merging**
