### PR TITLE
Fix: gitignore .idea and .vscode

### PR DESCRIPTION
**Pull request by edgarsn**
### What is the reason for this PR?

This helps to prevent from accidentally pushing IDE files while contributing to this repo.

- [ ] A new feature
- [x] Fixed an issue (No issue linked)

### Author's checklist

- [x] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [ ] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)

### Summary of changes

Added `/.idea/` and `/.vscode/` to `.gitignore` file to fix that.

### Review checklist

- [ ] All checks have passed
- [ ] Changes are approved by maintainer

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
These belong in your global gitignore file. It doesn't make sense for projects to duplicate this for each persons choice of OS and editor.

**Comment by pimjansen** [comment]
@GrahamCampbell do you know for any chance if there is an action to check this? It could help us to decline builds if stuff gets there

**Comment by GrahamCampbell** [comment]
I usually find that stuff is pretty easy to spot by eye when reviewing PRs.

**Comment by pimjansen** [comment]
> I usually find that stuff is pretty easy to spot by eye when reviewing PRs.

Fair but was just curious 👌🏻

**Pull request closed without merging**
