### PR TITLE
Add Central Kurdish Language

### PR DESCRIPTION
**Pull request by drpshtiwan**
### What is the reason for this PR?

- [x] A new feature
- [ ] Fixed an issue (resolve #ID)

### Author's checklist

- [x] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [ ] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)

### Summary of changes
I added Central Kurdish Language to the package.

### Review checklist

- [x] All checks have passed
- [ ] Changes are approved by maintainer

### CODE REVIEW

**Comment by pimjansen** [comment]
Please read the contribution guide. Since you checked the checkbox i assume you did.

'''

At the moment we are not looking for pull requests that add new features. We are planning for Faker 2.0's architecture.
'''

**Comment by drpshtiwan** [comment]
Thanks so much, I would be glad if you add my language to the package. When can I add the language?

**Comment by roj1512** [comment]
@drpshtiwan Seems like you have to wait until the 2.0 release.

**Comment by bram-pkg** [comment]
You should read the contribution guideline.

**Comment by drpshtiwan** [comment]
Ok thanks

**Pull request closed without merging**
