### PR TITLE
Add missing return type for some Generator methods

### PR DESCRIPTION
**Pull request by odolbeau**
### What is the reason for this PR?

Some methods does not have any return type.
PHPStan consider they return `mixed` and I have some "errors" in personal projects which use those methods.

### Author's checklist

- [x] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [x] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)

### Summary of changes

Add missing return type for some Generator methods

### Review checklist

- [ ] All checks have passed
- [x] Changes are added to the `CHANGELOG.md`
- [ ] Changes are approved by maintainer

### CODE REVIEW

**Comment by da-mask** [comment]
I'm not sure why , but this repo has a default branch of 2.0 (even though it seems abandoned) You might have better luck getting the pipeline to pass if you fork from the 1.x branch and create your PR against that.

**Comment by pimjansen** [comment]
This is also a BC which is not allowed besides a major release

**Comment by odolbeau** [comment]
@da-mask Thanks, branch changed! :ok_hand: 
@pimjansen Theoretically speaking, you're right, it is a BC Break. In practice, this won't break anything as those methods already return strings only. If you don't want to merge this PR on 1.x, I can move back this PR to 2.0 and make another one to add `@return` annotations on 1.x. WDYT?

**Comment by pimjansen** [comment]
Its a BC since you change the signature of a public non final method. Therefor it is not allowed

**Comment by odolbeau** [comment]
@pimjansen I made #923 to add some annotations.
Tell me if you want me to rebase this PR against 2.0 as proposed in my previous comment.

**Comment by pimjansen** [comment]
> @pimjansen I made #923 to add some annotations.
> 
> Tell me if you want me to rebase this PR against 2.0 as proposed in my previous comment.

I merged the other PR. 2.0 will be fully typed so no need to worry here

**Pull request closed without merging**
