### PR TITLE
Fix some SA issues and allow tools to be run locally easily

### PR DESCRIPTION
**Pull request by GrahamCampbell**
See title. ;)

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
BC Check warning is a false positive. The original phpdoc was incorrect.

**Comment by Nyholm** [comment]
Can you also update .gitattributes for the vendor-bin?

**Comment by GrahamCampbell** [comment]
Done. :)

**Review by Nyholm — APPROVED** [review]
Thank you

**Pull request merged**
