### PR TITLE
Enhancement: Enable strict_param fixer

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] enables the `strict_param` fixer
* [x] runs `make cs`
* [x] sets the parameter to `false` to retain current behaviour

Follows #157.

💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.2/doc/rules/strict/strict_param.rst.

### CODE REVIEW

**Comment by pimjansen** [comment]
Like this one though it could have some sidefx

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
👎 waste of time

**Comment by localheinz** [comment]
@pimjansen 

To play it safe, we could use `false` instead of `true` in all of these cases - what do you think?

Using the `strict_param` fixer, however, would ensure that in the future the parameter has to be set explicitly.

**Comment by pimjansen** [comment]
> @pimjansen 
> 
> 
> 
> To play it safe, we could use `false` instead of `true` in all of these cases - what do you think?
> 
> 
> 
> Using the `strict_param` fixer, however, would ensure that in the future the parameter has to be set explicitly.

Yeah agree. We can always review later on how to handle these cases or even do a Bc for faker 2

**Comment by localheinz** [comment]
@pimjansen 

> Yeah agree. We can always review later on how to handle these cases or even do a Bc for faker 2

Applied with 63270dc8baa49a18e6749293ccf886dec88d3bc7!

**Review by pimjansen — APPROVED** [review]

**Comment by localheinz** [comment]
Thank you, @pimjansen!

**Pull request merged**
